---
image: tmaier/docker-compose:latest
services:
 - docker:dind
stages:
 - build_and_push
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  LATEST_TAG: latest
  YAMLLINT_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE
cache:
  paths:
    - .cache/
    - venv/
build_dockerfiles:
  variables:
    DOCKER_DRIVER: overlay2
  stage: build_and_push
  cache: {}
  before_script:
      - docker-compose --version
      - docker version
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - echo "$CONTAINER_COMMIT_IMAGE"
    - docker build --pull -t $YAMLLINT_CONTAINER_RELEASE_IMAGE .
    - docker push $YAMLLINT_CONTAINER_RELEASE_IMAGE:$LATEST_TAG
