---
image: docker:stable
services:
  - docker:dind
stages:
  - linting
  - build_gitlab
  - build_hub
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  LATEST_TAG: latest
  HUB_RELEASE_IMAGE: docker.io/saltman33/ansible-yamllint
  YAMLLINT_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE
cache:
  paths:
    - .cache/
    - venv/
.linting: &linting
  stage: linting
yamllint:
  <<: *linting
  image: registry.gitlab.com/sultangillani/docker-yamllint:latest
  script:
    - yamllint -c ./.yamllint -f standard .
dockerfile_lint:
  <<: *linting
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint --config .hadolint.yaml Dockerfile
build_docker_gitlab:
  stage: build_gitlab
  before_script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - docker build --pull -t $YAMLLINT_CONTAINER_RELEASE_IMAGE .
    - docker push $YAMLLINT_CONTAINER_RELEASE_IMAGE:$LATEST_TAG
build_docker_hub:
  stage: build_hub
  before_script:
    - "docker login -u $HUB_USER -p $HUB_PW"
  script:
    - docker build --pull -t $HUB_RELEASE_IMAGE .
    - docker push $HUB_RELEASE_IMAGE:$LATEST_TAG
