---
version: '3.7'

services:
  yamllint:
    image: registry.gitlab.com/sultangillani/docker-yamllint:latest
    build:
      context: .
      cache_from:
        - registry.gitlab.com/sultangillani/docker-yamllint:latest
        - docker.io/saltman33/ansible-yamllint
    stdin_open: true
    tty: true
    container_name: yamllint
